    rule(
        id="GOV-RISK-004",
        title="Named diagnoses may appear as assertions only as clinician-approved conclusions",
        domain="high_risk_claim",
        status="provisional_needs_source",
        priority="P0",
        confidence="medium",
        data_class="clinician_approved_conclusion",
        source_evidence=[
            ev("walkthrough_2026_08_14", "00:33:56-00:34:09",
               "primarily with, okay, you have cardiovascular autonomic neuropathy, in this case, with isopathovagal balance, which means you should see a cardiologist. So, you know, we tell the clinician."),
            ev("walkthrough_2026_08_14", "00:34:48-00:35:10",
               "You also may have upper respiratory and pulmonary issues ... You may have pseudomotor dysfunction ... And then you have orthostatic dysfunction and possible syncope",
               note="Transcript 'pseudomotor' and 'isopathovagal' are almost certainly ASR errors for 'sudomotor' and 'sympathovagal'. Spelling is not assumed; see open questions."),
            ev("walkthrough_2026_08_14", "00:28:48-00:28:55",
               "Okay, so the blunted heart rate response indicates Neurogenic syncope."),
        ],
        trigger={
            "inputs": ["diagnosis.candidateLabels", "approval.records", "audience"],
            "description": "Any rendered surface that would state a named condition for a specific study.",
        },
        preconditions=[
            "A named condition (CAN, POTS, neurogenic syncope, sudomotor dysfunction, dysautonomia, orthostatic dysfunction) would otherwise be stated.",
        ],
        required_behavior=[
            "Engine and AI narrative use pattern-consistent-with framing only, with the missing-input limitation named.",
            "A named condition is stated as a conclusion only where an approval record shows a licensed clinician adopted that label for that study.",
            "Every asserted diagnosis carries the approving clinician identity and approval timestamp in the audit trail.",
        ],
        prohibited=[
            "Engine-authored 'you have <diagnosis>' text in any audience view.",
            "Definitive CAN / POTS / neurogenic syncope / sudomotor dysfunction assertions without an approval record.",
        ],
        dependencies=["GOV-RISK-001", "GOV-SCOPE-002", "GOV-SCOPE-004", "CLIN-VALS-002", "CLIN-STAND-002"],
        acceptance_criteria=[
            gwt("a study with no clinician approval records",
                "the diagnostic and impression sections render",
                "every condition is pattern-consistent-with framed and no named diagnosis is asserted"),
            gwt("a study where a clinician approved the label 'pattern consistent with cardiovascular autonomic neuropathy'",
                "the clinician-approved conclusion is rendered",
                "the label is attributed to the approving clinician with a timestamp and is the only asserted conclusion"),
        ],
        approval_owner="clinical_authority",
        open_questions=[
            "Confirm intended spelling and meaning of the two ASR-garbled terms ('pseudomotor' -> sudomotor?, 'isopathovagal' -> sympathovagal?).",
            "Which named conditions, if any, may the engine ever surface as candidates versus never mention at all?",
        ],
    ),
    rule(
        id="GOV-RISK-005",
        title="Therapy, supplement, pharmaceutical, dose and frequency content is clinician-entered only",
        domain="high_risk_claim",
        status="provisional_needs_source",
        priority="P0",
        confidence="medium",
        data_class="clinician_approved_conclusion",
        source_evidence=[
            ev("walkthrough_2026_08_14", "00:32:34-00:32:55",
               "we have a list of, you know, fluids and salts and compression garments, and alpha lipoic acid, and methylfolate, and all the things that we would recommend On the supplement side, and then go in and have possible recommendations for the pharmaceutical side, if we want to do that."),
            ev("walkthrough_2026_08_14", "00:33:27-00:33:50",
               "maybe we also put in there a space for, if approved, what's the dose? And what, you know, how many times a day do you do this and such? ... have the clinician just click, on The therapies, the dosages, and the frequency"),
            ev("walkthrough_2026_08_14", "00:32:05-00:32:08", "the clinician has implemented, not AI."),
        ],
        trigger={
            "inputs": ["therapy.menu", "therapy.approvals", "therapy.doseFields"],
            "description": "Therapy / supplement / pharmaceutical menu and any dose or frequency field.",
        },
        preconditions=[
            "A therapy, supplement, drug, dose or administration frequency would be displayed to any audience.",
        ],
        required_behavior=[
            "Dose and frequency are free/entered fields owned by the clinician; the engine pre-fills nothing.",
            "Any candidate therapy list shipped in the product is a fixed, reviewed catalogue, versioned and traceable to an approved source document.",
            "Patient-visible therapy content is emitted only from explicit clinician approval records.",
        ],
        prohibited=[
            "Engine-suggested or AI-suggested doses, frequencies, drug choices or supplement choices.",
            "Shipping the walkthrough's spoken example list as product content without documented source and legal/regulatory review.",
        ],
        dependencies=["GOV-SCOPE-002", "GOV-SCOPE-004", "PROD-PAT-002"],
        acceptance_criteria=[
            gwt("the therapy section for any fixture",
                "the section renders with no clinician input",
                "no dose, frequency, drug or supplement value is pre-populated and no AI-authored recommendation text appears"),
            gwt("a clinician approves two therapies and enters doses",
                "the patient-visible content is generated",
                "exactly those two therapies with exactly those clinician-entered doses appear, and nothing else"),
        ],
        approval_owner="legal_regulatory",
        open_questions=[
            "Is a shipped therapy catalogue in scope for the clinician-only first release, or is v1 free-text only?",
            "Who is the regulatory owner for a supplement/pharmaceutical catalogue inside a licensed product?",
        ],
    ),

    # ---------------- UX / usability ----------------
    rule(
        id="UX-CLIN-001",
        title="Classification states must be encoded in high-contrast distinct hues, not pastel shades",
        domain="visual_encoding",
        status="confirmed_in_review",
        priority="P1",
        confidence="high",
        data_class="system_behavior",
        source_evidence=[
            ev("walkthrough_2026_08_14", "00:20:52-00:21:12",
               "The color differentiation, too, like, below norm and above norm. They're almost ... the same color ... Yeah, you should just make it a different color, not a different shade."),
            ev("walkthrough_2026_08_14", "00:21:24-00:21:44",
               "Another reason why we went red, white, and blue is because red and blue and white and green are primary colors, and ... the contrasts are high. You get into these pastel colors, the contrasts are muted. And, you know, a lot of doctors are older doctors. They can't see the difference."),
        ],
        trigger={
            "inputs": ["chart.legend", "value.classification", "theme.tokens"],
            "description": "Any bar graph, legend or numeric cell that encodes in-band / below-norm / above-norm state.",
        },
        preconditions=[
            "A rendered element encodes classification state through colour.",
        ],
        required_behavior=[
            "Below-norm and above-norm use distinct hues (vendor convention: red / blue / white / green family), not two shades of one hue.",
            "Every colour-encoded state is also encoded non-chromatically (label, glyph or pattern).",
            "Legend text names each state explicitly (in band, below norm, above norm).",
        ],
        prohibited=[
            "Pastel or low-chroma palettes for classification state.",
            "Shade-only or colour-only differentiation of below-norm versus above-norm.",
        ],
        dependencies=["UX-A11Y-001", "UX-CLIN-004"],
        acceptance_criteria=[
            gwt("the clinician report for FIX-C01",
                "the classification legend and bars are sampled programmatically",
                "below-norm and above-norm swatches differ in hue by a fixed minimum angle and each state carries a text label"),
            gwt("a greyscale rendering of the same view",
                "classification state is read without colour",
                "every state remains distinguishable from label or glyph alone"),
        ],
        approval_owner="product_owner",
        open_questions=[
            "Confirm the exact approved palette tokens for in band / below norm / above norm against the vendor red-white-blue convention.",
        ],
    ),
    rule(
        id="UX-CLIN-002",
        title="Dense technical sections must be collapsed behind a visible disclosure control",
        domain="information_architecture",
        status="confirmed_in_review",
        priority="P1",
        confidence="high",
        data_class="system_behavior",
        source_evidence=[
            ev("walkthrough_2026_08_14", "00:11:45-00:12:06",
               "I guess because ... I don't see a down arrow for the time domain ratios. I do, you know, how this cardiorespiratory coupling. If the doctor wants to see it. you can pull it up, and I would do the same thing with time to mean ratios."),
            ev("walkthrough_2026_08_14", "00:12:11-00:12:19",
               "if a doctor does want to see it, they can click it. They don't. Right. The information's there if they want it, basically. / Exactly."),
            ev("walkthrough_2026_08_14", "00:23:53-00:23:57",
               "This is another one that should have a little arrow. As to whether or not the doctor wants to see it or not."),
        ],
        trigger={
            "inputs": ["section.id", "section.disclosureState"],
            "description": "Cardio-respiratory coupling, time-domain ratios, rhythm strip and comparable technical sections.",
        },
        preconditions=[
            "The section is classified as technical/optional in the section registry.",
        ],
        required_behavior=[
            "Each such section is collapsed by default with a visible, labelled disclosure affordance.",
            "Disclosure state is keyboard reachable and announced to assistive technology.",
            "Content is fully present in the DOM/report payload when expanded - collapsing must not drop data.",
        ],
        prohibited=[
            "A dense technical block rendered expanded by default with no affordance.",
            "A disclosure affordance on one technical section but not its siblings.",
        ],
        dependencies=["CLIN-RATIO-002", "UX-CLIN-003"],
        acceptance_criteria=[
            gwt("the clinician report for any cohort fixture",
                "the section registry is enumerated",
                "every section flagged technical is collapsed by default and exposes a labelled, focusable disclosure control"),
            gwt("a collapsed technical section",
                "the disclosure control is activated by keyboard",
                "the full section content renders and the state change is announced"),
        ],
        approval_owner="product_owner",
        open_questions=[],
    ),
    rule(
        id="UX-CLIN-003",
        title="Rhythm strip must be fully inspectable with legible ectopic annotation",
        domain="information_architecture",
        status="confirmed_in_review",
        priority="P1",
        confidence="high",
        data_class="measured_data",
        source_evidence=[
            ev("walkthrough_2026_08_14", "00:23:09-00:23:17",
               "Which we're not ... Gonna let them scroll through the rhythm strip, or the ... yeah, rhythm strip."),
            ev("walkthrough_2026_08_14", "00:23:17-00:23:30",
               "They should be able to, because it says so many ... it's got a blurry ... 13 atopic beats, noted. They appear as ... Clamped spikes?"),
            ev("walkthrough_2026_08_14", "00:23:44-00:23:51",
               "You got the whole strip, you should be able to screw it. / Yeah."),
        ],
        trigger={
            "inputs": ["ecg.strip", "ecg.ectopicAnnotations", "ecg.ectopicCount"],
            "description": "ECG rhythm strip section of the clinician report.",
        },
        preconditions=[
            "An ECG waveform array was parsed for the study.",
        ],
        required_behavior=[
            "The clinician can traverse the whole acquired strip, not only the first visible window.",
            "The annotated ectopic count is displayed and matches the deterministic parser count from the .ans annotation field.",
            "Annotation text is legible at the supported review resolutions.",
        ],
        prohibited=[
            "A fixed, non-traversable window presented as if it were the whole strip.",
            "An ectopic count in prose that disagrees with the parsed annotation value.",
        ],
        dependencies=["UX-CLIN-002", "CLIN-BASE-005", "GOV-PARITY-001"],
        acceptance_criteria=[
            gwt("a fixture whose .ans annotation reports N premature beats",
                "the rhythm strip section is expanded",
                "the displayed ectopic count equals N and the full strip duration is reachable"),
            gwt("the strip at the narrowest supported viewport",
                "annotations render",
                "annotation text meets the minimum legible size and does not overlap the trace"),
        ],
        approval_owner="engineering",
        open_questions=[
            "Does the clinician need per-beat ectopy markers on the strip, or only the aggregate count plus traversal?",
        ],
    ),
    rule(
        id="UX-CLIN-004",
        title="Classified graphs lead; the concise numeric table follows the explanations as a summary",
        domain="information_architecture",
        status="confirmed_in_review",
        priority="P2",
        confidence="medium",
        data_class="system_behavior",
        source_evidence=[
            ev("walkthrough_2026_08_14", "00:19:49-00:20:05",
               "Is it easy to look at this table, or is it easier to look at the graph? / the doctors ... It's easier to look at the graph because of these indications here. High, low, borderline low, critically low, etc."),
            ev("walkthrough_2026_08_14", "00:19:21-00:19:34",
               "The ANS Test Results Report. When we get down to this, after we've done all the explanations that we have above, As a summary. This would be the ... For a doctor, this would be the most concise way of summarizing ... that table."),
        ],
        trigger={
            "inputs": ["report.sectionOrder"],
            "description": "Top-level ordering of the clinician report.",
        },
        preconditions=[
            "Both classified graphs and the numeric summary table are present.",
        ],
        required_behavior=[
            "Classified graphs with named states (high, low, borderline low, critically low) precede raw numeric tables.",
            "The concise numeric table appears after the explanation sections as a summary.",
        ],
        prohibited=[
            "Leading the clinician report with an unclassified numeric matrix.",
        ],
        dependencies=["UX-CLIN-001", "UX-CLIN-005", "CLIN-DENS-001"],
        acceptance_criteria=[
            gwt("the clinician report for any cohort fixture",
                "section order is enumerated",
                "the classified graph sections precede the numeric summary table and the table follows the explanation sections"),
        ],
        approval_owner="clinical_authority",
        open_questions=[
            "Confirm the exact approved section order for the clinician report end to end.",
        ],
    ),
    rule(
        id="UX-CLIN-005",
        title="Every displayed number must carry a normal range or classification, or be removed",
        domain="information_architecture",
        status="confirmed_in_review",
        priority="P1",
        confidence="high",
        data_class="deterministic_calculation",
        source_evidence=[
            ev("walkthrough_2026_08_14", "00:20:29-00:20:45",
               "if you keep these numbers here and only bar graph a few of them, the doctor's gonna say, well, all right, is this 5.55 LFA at deep breathing, normal or abnormal? If it's ... if it's not necessarily necessary, why do you have it there?"),
        ],
        trigger={
            "inputs": ["table.cells", "cell.normalRange", "cell.classification"],
            "description": "Every numeric cell rendered in a clinician-facing table or panel.",
        },
        preconditions=[
            "A numeric value is rendered to a clinician.",
        ],
        required_behavior=[
            "Each rendered numeric cell carries either an explicit normal range or a classification state.",
            "Values with neither are removed from the view rather than shown bare.",
        ],
        prohibited=[
            "Bare numbers with no interpretive anchor.",
            "Silently deleting a value from the payload instead of the view (audit trail must retain it).",
        ],
        dependencies=["CLIN-DENS-001", "UX-CLIN-004"],
        acceptance_criteria=[
            gwt("the rendered clinician table for all cohort fixtures",
                "every numeric cell is enumerated",
                "each cell has a normal range or a classification state, and any exception is listed in an explicit approved allowlist"),
        ],
        approval_owner="clinical_authority",
        open_questions=[
            "Which cells, if any, are approved to display without a normal range?",
        ],
    ),
    rule(
        id="UX-CLIN-006",
        title="Retrieved source citations must be inspectable with document and page",
        domain="provenance_ux",
        status="product_direction",
        priority="P2",
        confidence="high",
        data_class="ai_narrative",
        source_evidence=[
            ev("walkthrough_2026_08_14", "00:18:04-00:18:19",
               "Click one, let's see what it does. / There's no clicking. / It is a reference, right? / But it gives the page numbers."),
        ],
        trigger={
            "inputs": ["answer.citations"],
            "description": "Citation chips under an Ask ATOM answer.",
        },
        preconditions=[
            "The answer surfaced at least one retrieved passage.",
        ],
        required_behavior=[
            "Each citation exposes the approved document title, edition and page range and can be opened to the retrieved passage text.",
            "Citations that cannot be resolved to an approved corpus document are not rendered; the answer abstains instead.",
        ],
        prohibited=[
            "Non-interactive citation chips whose provenance cannot be verified in-session.",
        ],
        dependencies=["GOV-RAG-001", "GOV-RAG-002"],
        acceptance_criteria=[
            gwt("an Ask ATOM answer with citations",
                "a citation is activated",
                "the exact retrieved passage, document title and page range are shown"),
        ],
        approval_owner="engineering",
        open_questions=[],
    ),
    rule(
        id="UX-A11Y-001",
        title="Clinician surfaces must be legible for reduced colour discrimination and older users",
        domain="accessibility",
        status="product_direction",
        priority="P1",
        confidence="medium",
        data_class="system_behavior",
        source_evidence=[
            ev("walkthrough_2026_08_14", "00:21:38-00:21:51",
               "a lot of doctors are older doctors. They can't see the difference. / I'm having a hard time differentiating between it on my monitor."),
        ],
        trigger={
            "inputs": ["theme.tokens", "typography.scale", "chart.encodings"],
            "description": "All clinician-facing rendering.",
        },
        preconditions=[
            "A clinician-facing view is rendered.",
        ],
        required_behavior=[
            "Text and essential graphical elements meet the project's documented minimum contrast target against their background.",
            "No information is conveyed by colour alone.",
            "Numeric labels and legends respect a minimum type size at the supported review resolutions.",
        ],
        prohibited=[
            "Contrast or type-size regressions in classification-bearing UI.",
        ],
        dependencies=["UX-CLIN-001"],
        acceptance_criteria=[
            gwt("the clinician report for FIX-C01 at the supported viewports",
                "automated contrast and type-size checks run",
                "no classification-bearing element falls below the documented thresholds"),
        ],
        approval_owner="product_owner",
        open_questions=[
            "Which contrast standard and level does PhysioPS want as the contractual target for the licensed product?",
        ],
    ),

    # ---------------- Operational defects and process ----------------
    rule(
        id="OPS-VOICE-001",
        title="Voice dictation into Ask ATOM truncates after roughly every second word",
        domain="defect_operational",
        status="confirmed_in_review",
        priority="P1",
        confidence="high",
        data_class="system_behavior",
        source_evidence=[
            ev("walkthrough_2026_08_14", "00:15:05-00:15:31",
               "Baseline A ... If baseline A [--] is corrupted. / I don't think it hurt you, probably because of my phone. / is corrupted.",
               note="Dictated question had to be restarted repeatedly."),
            ev("walkthrough_2026_08_14", "00:15:45-00:15:47",
               "Why does this keep turning off after every second word?"),
        ],
        trigger={
            "inputs": ["atom.voiceInput"],
            "description": "Clinician dictates a question into Ask ATOM.",
        },
        preconditions=[
            "Microphone permission granted; dictation session started.",
        ],
        required_behavior=[
            "A dictation session stays open until the user stops it or a documented silence timeout elapses.",
            "Partial transcripts accumulate into one coherent query rather than being cut into fragments.",
            "If the platform cannot sustain the session, the UI states the limitation instead of silently truncating.",
        ],
        prohibited=[
            "Silent session termination mid-utterance.",
        ],
        dependencies=[],
        acceptance_criteria=[
            gwt("an active dictation session on a supported clinician device",
                "a 20-word question is dictated with normal pauses",
                "the full question is captured in one query with no mid-utterance session termination"),
            gwt("a platform that cannot sustain continuous capture",
                "dictation is attempted",
                "an explicit limitation message is shown and no partial query is silently submitted"),
        ],
        approval_owner="engineering",
        open_questions=[
            "Which devices/browsers must be supported for dictation in the clinician-only release?",
        ],
    ),
    rule(
        id="OPS-EVID-001",
        title="Clinical review sessions require legible evidence capture",
        domain="process",
        status="product_direction",
        priority="P2",
        confidence="high",
        data_class="system_behavior",
        source_evidence=[
            ev("walkthrough_2026_08_14", "00:07:40-00:07:46",
               "it's ... you have it blurred here, but ... / I don't know what that is."),
            ev("walkthrough_2026_08_14", "00:23:25-00:23:30",
               "it's got a blurry ... 13 atopic beats, noted ... I can't ... it's kind of blurry, I can't really read it."),
        ],
        trigger={
            "inputs": ["review.session"],
            "description": "Any recorded clinical validation walkthrough used as governance evidence.",
        },
        preconditions=[
            "A recorded session is intended to produce binding clinical decisions.",
        ],
        required_behavior=[
            "Screen share resolution and scaling must render report text legibly in the recording.",
            "Each session produces a written decision list with timestamps, circulated for clinician confirmation.",
        ],
        prohibited=[
            "Treating an illegible on-screen artifact as reviewed and approved.",
        ],
        dependencies=[],
        acceptance_criteria=[
            gwt("a recorded review session",
                "the recording is sampled at each decision point",
                "the report text under discussion is legible, or the decision is marked unverified pending re-review"),
        ],
        approval_owner="product_owner",
        open_questions=[],
    ),
    rule(
        id="OPS-PLAN-001",
        title="Calendar-year delivery commitment and engineering attendance risk are tracked, not gated",
        domain="process",
        status="product_direction",
        priority="P3",
        confidence="high",
        data_class="system_behavior",
        source_evidence=[
            ev("walkthrough_2026_08_14", "00:37:32-00:38:00",
               "Unfortunately, there's still a lot of work to do. / Very unfortunately, yes. ... I've sort of committed us, in a sense. To having all this done by the end of the calendar year."),
            ev("walkthrough_2026_08_14", "00:38:15-00:38:29",
               "My concern is, as in the past. ... Ben's supposed to be here, and he's not. Yeah, we do have a reliability issue."),
        ],
        trigger={
            "inputs": [],
            "description": "Programme management context, recorded for completeness.",
        },
        preconditions=[
            "None. This is non-clinical context.",
        ],
        required_behavior=[
            "The end-of-calendar-year commitment and the engineering availability risk are tracked in the programme plan.",
        ],
        prohibited=[
            "Using schedule pressure as justification to ship any rule in provisional_needs_source or needs_clinician_wording status.",
        ],
        dependencies=[],
        acceptance_criteria=[
            gwt("a release candidate proposed under schedule pressure",
                "the stop-ship checklist is evaluated",
                "no stop-ship criterion is waived on schedule grounds"),
        ],
        approval_owner="product_owner",
        open_questions=[],
    ),

    # ---------------- Product direction (patient experience) ----------------
    rule(
        id="PROD-PAT-001",
        title="Patient experience is a separate, simple destination added after the clinician release",
        domain="product_scope",
        status="product_direction",
        priority="P2",
        confidence="high",
        data_class="patient_visible_content",
        source_evidence=[
            ev("walkthrough_2026_08_14", "00:31:12-00:31:26",
               "Well, at some point in time, we need a patient map of some sort. ... I think we need a patient app of some sort."),
            ev("walkthrough_2026_08_14", "00:31:33-00:31:51",
               "We can always add a patient specific ones. ... they're two separate sites, basically, right? / Yes, definitely. / and then the patient one is just ... Really simple."),
        ],
        trigger={
            "inputs": ["deployment.surface"],
            "description": "Deployment topology for patient-facing content.",
        },
        preconditions=[
            "The clinician-only release has shipped.",
        ],
        required_behavior=[
            "The patient experience is a distinct surface with its own content contract, not a view toggle inside the clinician tool.",
            "The patient surface is deliberately minimal.",
        ],
        prohibited=[
            "Reusing the clinician report body as patient content.",
        ],
        dependencies=["GOV-SCOPE-001", "GOV-SCOPE-002"],
        acceptance_criteria=[
            gwt("the clinician-only release",
                "the deployment surfaces are enumerated",
                "no patient surface is reachable and no patient/clinician toggle exists"),
        ],
        approval_owner="product_owner",
        open_questions=[],
    ),
    rule(
        id="PROD-PAT-002",
        title="Clinician approve/decline controls are the only channel that populates patient content",
        domain="product_scope",
        status="product_direction",
        priority="P1",
        confidence="high",
        data_class="clinician_approved_conclusion",
        source_evidence=[
            ev("walkthrough_2026_08_14", "00:32:55-00:33:18",
               "have boxes ... two boxes on the ... in the right-hand, margin that says approve or disappro ... approve or not. ... And every box that the clinician approves, automatically ... Gets input to the patient side."),
            ev("walkthrough_2026_08_14", "00:34:22-00:34:29",
               "And then the doctor clicks on the things that he would approve of, and that gets sent over to the patient."),
        ],
        trigger={
            "inputs": ["approval.records", "patient.contentBuilder"],
            "description": "Generation of any patient-visible content item.",
        },
        preconditions=[
            "An approval record exists identifying the approving clinician, the item and the timestamp.",
        ],
        required_behavior=[
            "Patient content is a pure function of approval records plus clinician-entered fields.",
            "Declining an item removes it from patient content with an audit entry.",
        ],
        prohibited=[
            "Any patient-visible item without a matching approval record.",
        ],
        dependencies=["GOV-SCOPE-002", "GOV-SCOPE-004", "GOV-RISK-005"],
        acceptance_criteria=[
            gwt("a study with three candidate items where the clinician approves one and declines two",
                "patient content is generated",
                "exactly the approved item appears and both declined items are absent with audit entries"),
            gwt("an approval record deleted after generation",
                "patient content is regenerated",
                "the corresponding item disappears from patient content"),
        ],
        approval_owner="clinical_authority",
        open_questions=[],
    ),
    rule(
        id="PROD-PAT-003",
        title="Patients may download their full data behind an explicit physician-interpretation gate",
        domain="product_scope",
        status="product_direction",
        priority="P2",
        confidence="medium",
        data_class="patient_visible_content",
        source_evidence=[
            ev("walkthrough_2026_08_14", "00:35:43-00:36:03",
               "there has to be a back door somewhere on the patient report that says, okay, if you want all of your information ... click here and download. But remember, it's not valid without a physician reading."),
            ev("walkthrough_2026_08_14", "00:36:07-00:36:28",
               "the doctor may not agree with anything ... and then the patient needs to go find another doctor. So you need to give the patient their data in order to do so"),
        ],
        trigger={
            "inputs": ["patient.downloadRequest"],
            "description": "Patient requests the full data package.",
        },
        preconditions=[
            "The patient surface exists (post clinician-only release) and the requester is the patient of record.",
        ],
        required_behavior=[
            "The download provides the underlying data artifacts the patient is entitled to.",
            "The download is gated by the physician-interpretation disclaimer of GOV-DISC-003 and the download event is audited.",
        ],
        prohibited=[
            "Attaching engine-authored narrative conclusions to the downloaded package.",
        ],
        dependencies=["GOV-DISC-003", "GOV-SCOPE-002", "PROD-PAT-001"],
        acceptance_criteria=[
            gwt("a patient requesting the full data package",
                "the download is initiated",
                "the physician-interpretation disclaimer is displayed and acknowledged, the artifacts contain no engine-authored conclusions, and the event is audited"),
        ],
        approval_owner="legal_regulatory",
        open_questions=[
            "Which artifacts exactly are in the patient download package, and under which jurisdiction's access rules?",
        ],
    ),
]
